

name: My Github Actions

on:
 
  push:
    branches: 
     - main
      
 
jobs:
  my_testing:
    runs-on: ubuntu-latest
   
    steps:
     
       - id: Hello
         run: "AA=Hello"
   
    
     
       - id: World
         run: echo ${{ steps.Hello.AA.World }}
       
   
   
        
        
        
