name: My Github Actions

on:
 
  push:
    branches: 
     - main
      
 
jobs:
  my_testing:
    runs-on: ubuntu-latest
   
    steps:
     
       - id: barev
         run: echo "AA=Hello" >> $GITHUB_OUTPUT
         
       - id: ashxarh
         run: echo "BB=world" >> $GITHUB_OUTPUT
  
     
    
       - run: echo ${{ steps.barev.outputs.AA }} ${{ steps.ashxarh.outputs.BB }}
       
   
   
        
        
        
