

name: My Github Actions

on:
 
  push:
    branches: 
     - master
      
 
jobs:
  my_testing:
   runs-on: ubuntu-latest
   
   steps:
     - name: Barev
       run: echo "Barev inchx es"
        
        
        
