

name: My Github Actions

on:
 
  push:
    branches: 
     - main
      
 
jobs:
  my_testing:
    runs-on: ubuntu-latest
   
    steps:
     - name: Barev
       
       run: |
         echo "Barev inchx es"
       
  my-testing2:
  
     runs-on: ubuntu-latest
   
     needs: [my_testing]
   
     steps:
     - name: lav em
       run: echo "Es el em lav, du inchx es"
       
   
   
        
        
        
