

name: My Github Actions

on:
 
  push:
    branches: 
     - main
      
 
jobs:
  my_testing:
    runs-on: ubuntu-latest
   
    steps:
     
       - id: Hello
         run: echo "AA=Hello" >> $GITHUB_OUTPUT
   
    
     
       - id: World
         run: echo ${{ steps.Hello.outputs.AA }}
       
   
   
        
        
        
